### ISSUE TITLE
Login security features

### ISSUE THREAD

**Issue by Lan-Li-Jenny** [nuBuilder/nuBuilder-4.5#1]
To prevent login attacks, it would probably be wise to implement something like this:

- Rate limiting of logins per IP address > Redirect to a page: "You're doing this too much..."
- Locking accounts after 3 failed login attempts > Prevent future logins and redirect to a page for password reset
- Password reset procedure. (I believe this is being worked on)

( Only used nuBuilder for two weeks now, has been great so far. Amazingly well done! )

**Comment by smalos** [comment]
Thanks for your inputs!

You could create a (PHP) Procedure and call it nuStartup. In there you can log activities and take the necessary action.

Password reset procedure: Check out "nuBuilder 4 - Self-Service Password Reset":
https://github.com/smalos/nubuilder-password-recovery
