### ISSUE TITLE
Possible vulnerability: nupmalogin.php passes plaintext DB password as cookie

### ISSUE THREAD

**Issue by RussellAult** [nuBuilder/nuBuilder-4.5#12]
Currently, nuBuilder passes the DB login information, including the plaintext password, to phpMyAdmin by setting a cookie on the client computer. Anyone who can access this cookie (i.e. anyone with access to the file system where the browser stores cookies) is able to read the DB login information, which could potentially result in the DB being compromised.

I'm not yet totally familiar with how phpMyAdmin integrates with nuBuilder, but surely it would be more secure to read these configuration options directly `nuconfig.php`? At least this way the DB login info never leaves the server.

**Comment by smalos** [comment]
Thanks for your input. I'm going to review that process and evaluate other possibilities.

**Comment by smalos** [comment]
The DB parameters are now retrieved from nuconfig.php instead of setting a cookie.
