### ISSUE TITLE
[Feature Request] Add $nuConfigDBOptions to nuconfig.php

### ISSUE THREAD

**Issue by RussellAult** [nuBuilder/nuBuilder-4.5#13]
It would be great if there was an easy way to specify additional PDO options within `nuconfig.php`. The immediate use-case for this is for enabling SSL connections, but there might be others, too.

**Comment by smalos** [comment]
The latest version allows you to specify additional PDO options in nuconfig.php:

E.g.

`$nuConfigDBOptions = array(PDO::ATTR_PERSISTENT => true);`
