### ISSUE TITLE
Input field length limit property needed

### ISSUE THREAD

**Issue by zajc3w** [nuBuilder/nuBuilder-4.5#2]
Currently input fields have unlimited? entry length.
It would be nice to have an option to set limit in properties.
Autodetecting table field length would be ultimate but probably very complicated to implement.

**Comment by pmjd-code** [comment]
Not built-in but there something in the code library for nuBuilder, which allows you to limit the number of characters in a text input field.

https://github.com/nuBuilder/nuBuilder-4.5-Code-Library/tree/master/codelib/object_limit_characters

**Comment by smalos** [comment]
The maxlength attribute is now set by retrieving the length of the DB column.

**Comment by zajc3w** [comment]
AWESOME!!
Thank You
