### ISSUE TITLE
The report does not support utf-8？

### ISSUE THREAD

**Issue by weinsheimer** [nuBuilder/nuBuilder-4.5#20]
Example from Pizza Tutorial on nuBuilder 4.5

[Invoice screenshot, utf-8 representation is correct](https://img-blog.csdnimg.cn/39ef6f5856cb45e498d04cd6cec4e832.png)

[Build report screenshot, utf-8 representation is correct](https://img-blog.csdnimg.cn/b7d7ad770b2448c48fab7dcc9976818f.png#pic_center)

[The report with ?? for utf-8 character](http://xx-docs.oneshanghai.cn/nu/nureport.pdf)

**Comment by smalos** [comment]
You will probably need a unicode supporting font, see https://stackoverflow.com/questions/8737772/tcpdf-encode-chinese-character
