### ISSUE TITLE
How to configure access levels to objects

### ISSUE THREAD

**Issue by criszalo1997** [nuBuilder/nuBuilder-4.5#22]
Hello devs, I'm new to nuBuilder, I like the ease and flexibility, but I have a problem, how can I configure a level of access to an object such as an input text or a button, in such a way that a user can have access to a form but not access or can not see certain parts such as buttons or inputs.

It would be ideal to set access levels as forms have but at the object level.

**Comment by smalos** [comment]
You will have to use JS to do so.

**Comment by criszalo1997** [comment]
Thank you for answering, could you provide me with an example, it would also be a good idea to integrate something like this in the future and for the next time I will raise a situation in your forum, greetings
