### ISSUE TITLE
What is Email & Password?

### ISSUE THREAD

**Issue by riubotin-project** [nuBuilder/nuBuilder-4.5#24]
Hello Sir, I run nuBuilder-4.5 in local host. when I open the project, just show me Login form. no link to register or anything.
https://prnt.sc/hcCXEaxL4CLr

**Comment by smalos** [comment]
The default admin user credentials:

User: globeadmin
Password: nu

They can be changed in nuconfig.php

**Comment by riubotin-project** [comment]
Thanks Kevin, I found it in readme file.. it solved.. 🙏

Pada tanggal Kam, 2 Jun 2022 9.58 AM, kev1n ***@***.***>
menulis:
