### ISSUE TITLE
how to delete a form?

### ISSUE THREAD

**Issue by ecsuae** [nuBuilder/nuBuilder-4.5#25]
sorry for dumb question , how to delete a form from "user home"?

**Comment by smalos** [comment]
To delete the form without its object: Open the form, the in the Options Menu -> Form Properties, the hit "Delete".

To delete a form and all its objects its:
https://github.com/nuBuilder/nuBuilder-4.5-Code-Library/tree/master/codelib/globeadmin_delete_form_and_data
