### ISSUE TITLE
nuBuilder "lookup" not working properly

### ISSUE THREAD

**Issue by m2acgi** [nuBuilder/nuBuilder-4.5#28]
Hi team, thank you for your great software product. The value of "lookup" is ok after select, but it's not what I want after click the "Save" button. I want to dispaly/stor the value after lookup select.

Sorry for my poor English. Please check the gif screenshot. Click the right top corner play button to paly.

![2022-07-18_16-53-18](https://user-images.githubusercontent.com/34497122/179478653-233c9a6b-9e44-4173-a6f7-f480ca652273.gif)

**Comment by smalos** [comment]
Hi, you will need to use a join in the Browse SQL to retrieve the department name and display it instead of the id.

**Comment by m2acgi** [comment]
Thanks. Where's the sample code to do this? I can't found in then docs.

**Comment by smalos** [comment]
Here's an example together with the table schemas.

![browse_sql](https://user-images.githubusercontent.com/45562597/180429989-35abfd9e-6c1a-4e2c-bb5c-238566a64fca.png)
![person](https://user-images.githubusercontent.com/45562597/180429994-04800ace-d2f4-472e-b03c-609c43fc3ac2.png)
![department](https://user-images.githubusercontent.com/45562597/180429996-01011920-ace1-46e9-815c-d8bc1ccf012f.png)

**Comment by smalos** [comment]
Please let me know if that helps or if you need further information.

**Comment by m2acgi** [comment]
:thumbsup: Thanks a lot!
