### ISSUE TITLE
Uncaught Error: Call to undefined function nuHash()

### ISSUE THREAD

**Issue by GaneshKandu** [nuBuilder/nuBuilder-4.5#29]
**✪ Easy installation:**

- Download and unzip the nuBuilder files from https://github.com/nuBuilder/nuBuilder-4.5/
- Upload to your webserver
- Create a database (e.g. nubuilder4) and optionally a user
- Make a copy of the nuconfig-sample.php file and save the new file as nuconfig.php
- Edit nuconfig.php to set your database and globeadmin credentials
- Open the URL that will look something like: http://yoursitename.com/nubuilder4/index.php
- Done - you can now login as 'globeadmin'

After Following this step when i tried to login i got blank page

with this error

```
Array
(
    [type] => 1
    [message] => Uncaught Error: Call to undefined function nuHash() in /home/user/public_html/nubuilder/core/nudatabase.php:360
Stack trace:
#0 /home/user/public_html/nubuilder/core/nudatabase.php(418): nuDebugResult('2022-07-26 11:1...')
#1 /home/user/public_html/nubuilder/core/nudatabase.php(136): nuDebug('===USER========...')
#2 /home/user/public_html/nubuilder/index.php(106): nuRunQuery('SELECT * FROM z...')
#3 /home/user/public_html/nubuilder/index.php(221): nuHeader()
#4 {main}
  thrown
    [file] => /home/user/public_html/nubuilder/core/nudatabase.php
    [line] => 360
)
```

**Comment by smalos** [comment]
Hi, could you try again with the latest files ( https://github.com/nuBuilder/nuBuilder-4.5/archive/refs/heads/master.zip ) ?
