### ISSUE TITLE
Memory exhausted - no login screen rendered

### ISSUE THREAD

**Issue by Sebadier** [nuBuilder/nuBuilder-4.5#3]
After setting up the DB and copying the nuBuilder files into the web folder I always get:

Fatal error: Allowed memory size of XXX exhausted (tried to allocate 20480 bytes) in /var/www/vhosts/XXX/httpdocs/core/nudatabase.php on line 66

Raising the php memory limit does not help. Also the line number in the error log varies between 66, 61 and 70.
I am using MariaDB and tried PHP7.2 and PHP7.3

This might be a setup problem, I installed all necessary php modules though.

**Comment by smalos** [comment]
Please try again with the latest version.
