### ISSUE TITLE
PHP 8.1 Not Supported

### ISSUE THREAD

**Issue by respectTheCode** [nuBuilder/nuBuilder-4.5#32]
The docs make it seem like anything 7.1 or newer should work. I tried running with with 8.1.11 but ran into a wall of warnings and errors. After downgrading to 7.4.32 everything appears to be working.

**Comment by neilromig** [comment]
I'm using it with 8.1.11 and no problems.

**Comment by smalos** [comment]
I don't see any issues with 8.1.2 either. What warnings do you see?

**Comment by smalos** [comment]
Close issue since no response.

**Comment by smalos** [comment]
PHP 8.1. compatibility issues have been fixed.
