### ISSUE TITLE
fast form not able to add to user home after first fast form deleted

### ISSUE THREAD

**Issue by francoismuller2** [nuBuilder/nuBuilder-4.5#37]
Hello, 
I'm a new user of nubuilder forte.
I tried to play around to see how it works:
- I created a fast form that created the green user home button
- I deleted this form and the green button disappeared
- now when I create a new fast form, it still say success but if I click on the popup link it says "Uncaught Error."
- the green button no more appear
any idea how to fix this ?

Regards

**Comment by smalos** [comment]
The userhome is a core form. Run the update button to restore the core form.

**Comment by smalos** [comment]
If you have any further questions, please post them in the nuBuilder forum.
