### ISSUE TITLE
Cleaning the form after save(submit)

### ISSUE THREAD

**Issue by NetLancer** [nuBuilder/nuBuilder-4.5#44]
Hi guys! 
Strange to me, but i couldn't find in docs, in JS API reference the method for cleaning the form. 
The values remain in respective fields by default while saving's successful .. 
Need help/someClue/rightLink :)

**Comment by smalos** [comment]
Hi,

Call nuReturnNewRecord() in the AS event to return a new record after saving:

https://wiki.nubuilder.cloud/index.php?title=PHP#nuReturnNewRecord
