### ISSUE TITLE
The gettype returns string even when the value is 2

### ISSUE THREAD

**Issue by mantisae** [nuBuilder/nuBuilder-4.5#56]
broken in commit 9c5c734

var_dump returns [3]=> String(1) "2" in all of my reports formatted as $ 1,000.00 (or anything else with decimals) the regular forms seem to be correct still.

uncommenting 1003 and commenting out 1004 fixes the reports.

https://github.com/nuBuilder/nuBuilder-4.5/blob/9c5c7343023d0ee0a080532aee3091b94c486f20/core/nucommon.php#L1004

**Comment by smalos** [comment]
PR from 4 days reverted, need to investigate fuhrer.
