### ISSUE TITLE
Unable to delete records

### ISSUE THREAD

**Issue by mantisae** [nuBuilder/nuBuilder-4.5#57]
needs to be changed to nuStartsWith
https://github.com/nuBuilder/nuBuilder-4.5/blame/3bd90a1f4e4e1dbfe1a7d915b3bc1995d8d923ec/core/nuform.js#L5143

subform deletes seem to still work

**Comment by mantisae** [comment]
On a second go round I'm finding that it's only complaining if I don't access the record from the browse form.  I have links in a generated html box `<a onclick="nuForm('5de7faa79bb6ec4', 5390, '', '', 0)" href="">Action Verification: Repair</a>` and if I open the record from one of them I get no delete confirmation and the row doesn't delete even if I refresh it.

**Comment by smalos** [comment]
How can I reproduce it? e.g. add a new record to "Notes", then click on "delete"?

And which version are you using? 

Does the behaviour also occur with the current version?
https://github.com/nuBuilder/nuBuilder-4.5/archive/refs/heads/master.zip

**Comment by mantisae** [comment]
DB: V.4.5-2024.03.08.01
Files: V.4.5-2024.03.08.15
Updated to
Files Version: V.4.5-2024.03.08.14
Files Version: V.4.5-2024.03.08.15

clicking run setup button on my customers current rentals subform -> inserts initial charges and adds setup appt to schedule (along with a link in the notes on that rental to the schedule) then brings up popup showing the schedule appt to add time and or extra notes -> opening the billing screen for the rental 
![Screen Shot 2024-03-08 at 2 11 34 PM](https://github.com/nuBuilder/nuBuilder-4.5/assets/1761267/aad42316-d139-4295-98da-d41fcef5ebef)
![Screen Shot 2024-03-08 at 2 12 36 PM](https://github.com/nuBuilder/nuBuilder-4.5/assets/1761267/05c64266-5e29-402c-a117-43dfad445565)
![Screen Shot 2024-03-08 at 2 15 25 PM](https://github.com/nuBuilder/nuBuilder-4.5/assets/1761267/f411cb96-ecb7-43e5-b265-bbc5e73591a3)
![Screen Shot 2024-03-08 at 2 16 45 PM](https://github.com/nuBuilder/nuBuilder-4.5/assets/1761267/0fa7825a-1526-47cc-b981-9f7a01c51dab)

**Comment by smalos** [comment]
The question remains, how can I reproduce it ?
Does deleting work in general but just not with one specific form?

**Comment by mantisae** [comment]
deleting works with that form as long as you reach it through the browse form clicking on my anchor takes you there and allows you to modify and save but not delete.  I only have 1 other form that users are allowed to delete from and it is only accessible from a browse form. It works there if you save the initial record then back out to the browse form and re-enter the record before you can delete it.

**Comment by mantisae** [comment]
That may be the difference all of my PKs are mysql auto increment fields since most of the data was brought over from an MS Access DB

**Comment by smalos** [comment]
I pushed a fix that should fix it:

https://github.com/nuBuilder/nuBuilder-4.5/commit/5b4ce89fbc5be7d0b7a6a16370a432eb35fb30cf

**Comment by mantisae** [comment]
fixed
