### ISSUE TITLE
Users from external source of authentication like LDAP, AD, SQL database

### ISSUE THREAD

**Issue by TeaM-TL** [nuBuilder/nuBuilder-4.5#58]
Would be nice to use external source of authentication like LDAP or Active DIrectory or external SQL database to avoid duplication users

**Comment by smalos** [comment]
Thank you for sharing your suggestion regarding the use of external sources. While we currently do not have plans to implement this feature in the near future, we always appreciate feedback from our users. Contributions in the form of pull requests (PRs) are always welcome!

**Comment by smalos** [comment]
Moving to internal do-do list
