### ISSUE TITLE
Unable to dbl click on readonly fields

### ISSUE THREAD

**Issue by mantisae** [nuBuilder/nuBuilder-4.5#60]
I used to be able to dbl click on readonly & display fields (I have specific ondblclick events on them) at some point the readonly fields stopped working and since it wasn't something I used often I didn't notice it, one of the recent updates though broke dbl clicking on a display field for my click to call system.  Could we have a way to allow dbl clicking on readonly & display fields with an ondblclick event back?

Thank you

**Comment by smalos** [comment]
Try removing the disabled attribute:
` $('#your_displayfield_id').removeAttr('disabled');`

**Comment by mantisae** [comment]
That works
